export const users = [
  {
    _id: '678755b18e8532893777eaf9',
    index: 0,
    guid: 'd471ded8-a94f-4f1f-8e80-1a17f5ce5485',
    isActive: false,
    balance: '$1,753.37',
    picture: 'http://placehold.it/32x32',
    age: 23,
    eyeColor: 'green',
    name: 'Gracie Howard',
    gender: 'female',
    company: 'TWIGGERY',
    email: 'graciehoward@twiggery.com',
    phone: '+1 (983) 560-2575',
    address: '995 Greene Avenue, Tibbie, Alaska, 750',
    about:
      'Laborum ipsum aliquip excepteur nulla. Aliquip occaecat laborum laborum aliquip quis fugiat in sunt deserunt eu ipsum. Qui consectetur id nisi ipsum eiusmod. Ut elit quis adipisicing deserunt in veniam irure aute elit occaecat adipisicing velit esse.\r\n',
    registered: '2015-04-25T11:29:13 -05:00',
    latitude: 17.377578,
    longitude: -175.432542,
    tags: ['pariatur', 'ea', 'id', 'consequat', 'quis', 'dolor', 'Lorem'],
    friends: [
      {
        id: 0,
        name: 'Hannah Hansen',
      },
      {
        id: 1,
        name: 'Rosanne Hardy',
      },
      {
        id: 2,
        name: 'Summers Hancock',
      },
    ],
    greeting: 'Hello, Gracie Howard! You have 2 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '678755b103747957f89e5545',
    index: 1,
    guid: 'f8acf757-3d1f-49c9-ae66-ef68dbdd7e25',
    isActive: true,
    balance: '$2,839.74',
    picture: 'http://placehold.it/32x32',
    age: 34,
    eyeColor: 'green',
    name: 'Marissa Hamilton',
    gender: 'female',
    company: 'ARTIQ',
    email: 'marissahamilton@artiq.com',
    phone: '+1 (850) 489-3295',
    address: '473 Kenmore Terrace, Beaulieu, North Dakota, 2317',
    about:
      'Velit deserunt adipisicing non reprehenderit id ea labore et aliquip ipsum. Ex id proident quis sint esse eu in veniam. Non laborum irure culpa dolor irure eu. Sunt exercitation velit tempor irure ut voluptate enim dolor officia incididunt ut. Lorem sunt dolore irure ex ut officia et. Minim tempor amet magna eu id esse id quis non elit laboris Lorem.\r\n',
    registered: '2016-12-20T02:04:50 -05:00',
    latitude: 36.594266,
    longitude: 169.856789,
    tags: [
      'eiusmod',
      'consectetur',
      'nisi',
      'minim',
      'minim',
      'labore',
      'minim',
    ],
    friends: [
      {
        id: 0,
        name: 'Madden Wheeler',
      },
      {
        id: 1,
        name: 'Belinda Moran',
      },
      {
        id: 2,
        name: 'Madeleine Garza',
      },
    ],
    greeting: 'Hello, Marissa Hamilton! You have 1 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '678755b1257f8358b5fdff04',
    index: 2,
    guid: 'e8841ae7-d39e-44f0-bc73-081fc7360695',
    isActive: false,
    balance: '$2,797.45',
    picture: 'http://placehold.it/32x32',
    age: 26,
    eyeColor: 'green',
    name: 'Nelda Mclaughlin',
    gender: 'female',
    company: 'ZOARERE',
    email: 'neldamclaughlin@zoarere.com',
    phone: '+1 (826) 445-3443',
    address: '100 Woodruff Avenue, Fowlerville, Pennsylvania, 4736',
    about:
      'Elit ad occaecat eiusmod excepteur minim officia amet eiusmod. Cupidatat enim Lorem mollit id dolore ullamco. Sint id cupidatat sint eu incididunt non est id est. Laborum ut irure exercitation minim in eu esse. Velit tempor magna voluptate reprehenderit irure laborum esse fugiat ex ex esse est elit. Et ad ipsum duis mollit amet fugiat consectetur veniam.\r\n',
    registered: '2019-12-07T02:26:36 -05:00',
    latitude: 5.479258,
    longitude: 124.630745,
    tags: ['culpa', 'laborum', 'ea', 'nulla', 'eiusmod', 'est', 'consequat'],
    friends: [
      {
        id: 0,
        name: 'Mcleod Strong',
      },
      {
        id: 1,
        name: 'Mcdonald Christian',
      },
      {
        id: 2,
        name: 'Powell Miles',
      },
    ],
    greeting: 'Hello, Nelda Mclaughlin! You have 8 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '678755b118e6273a0a0c9998',
    index: 3,
    guid: 'd5f80606-79bd-4e1f-b7ee-c06eb72696b9',
    isActive: true,
    balance: '$1,046.94',
    picture: 'http://placehold.it/32x32',
    age: 40,
    eyeColor: 'brown',
    name: 'Mullen Schmidt',
    gender: 'male',
    company: 'APPLIDEC',
    email: 'mullenschmidt@applidec.com',
    phone: '+1 (986) 518-2851',
    address: '633 Post Court, Maybell, Maine, 3868',
    about:
      'Sunt aute nostrud commodo nisi quis non eiusmod consequat. Irure sit sint consectetur ullamco eu id ipsum amet quis nostrud consequat. Lorem proident reprehenderit nostrud laborum minim officia ut velit ut fugiat aliqua. Laboris ut cillum duis id cillum. Enim et ullamco et tempor commodo do. Voluptate occaecat et reprehenderit occaecat aute velit consectetur cupidatat dolore nulla do.\r\n',
    registered: '2022-01-24T04:41:22 -05:00',
    latitude: -2.059401,
    longitude: -30.523596,
    tags: ['ex', 'consectetur', 'velit', 'consequat', 'non', 'non', 'et'],
    friends: [
      {
        id: 0,
        name: 'Roberts Moses',
      },
      {
        id: 1,
        name: 'Salas Nelson',
      },
      {
        id: 2,
        name: 'Hammond Winters',
      },
    ],
    greeting: 'Hello, Mullen Schmidt! You have 10 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '678755b1867be93df532c4b8',
    index: 4,
    guid: '6f55653a-3134-4c23-b05a-d31c565ccc97',
    isActive: true,
    balance: '$1,177.05',
    picture: 'http://placehold.it/32x32',
    age: 24,
    eyeColor: 'green',
    name: 'Guy Brady',
    gender: 'male',
    company: 'FLUM',
    email: 'guybrady@flum.com',
    phone: '+1 (905) 438-2780',
    address: '322 Lacon Court, Hackneyville, Massachusetts, 9020',
    about:
      'Aute sunt qui nisi et ut magna ad elit nisi incididunt laborum enim eiusmod. Veniam est qui labore officia occaecat magna aliqua proident velit laborum laboris. Veniam velit incididunt officia amet velit mollit nulla quis anim enim voluptate esse. Elit proident ut amet do adipisicing ipsum id deserunt.\r\n',
    registered: '2015-03-22T12:18:43 -05:00',
    latitude: -74.329223,
    longitude: 153.14632,
    tags: ['eu', 'sint', 'fugiat', 'elit', 'proident', 'et', 'sit'],
    friends: [
      {
        id: 0,
        name: 'Hart Carrillo',
      },
      {
        id: 1,
        name: 'Cohen Mcmahon',
      },
      {
        id: 2,
        name: 'Maude Knowles',
      },
    ],
    greeting: 'Hello, Guy Brady! You have 3 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '678755b1f6c098e142ad8f3b',
    index: 5,
    guid: 'f5f6c4db-3f6e-4db5-950c-a033d99f6648',
    isActive: true,
    balance: '$2,892.88',
    picture: 'http://placehold.it/32x32',
    age: 39,
    eyeColor: 'green',
    name: 'Cathryn Booth',
    gender: 'female',
    company: 'ACCUFARM',
    email: 'cathrynbooth@accufarm.com',
    phone: '+1 (991) 444-2852',
    address: '215 Varick Street, Lupton, Federated States Of Micronesia, 5024',
    about:
      'Do amet et ipsum minim irure. Non deserunt Lorem esse minim qui enim nostrud ullamco mollit. Nulla do sint veniam reprehenderit irure consectetur labore enim ea officia sit deserunt fugiat reprehenderit. Incididunt irure laborum proident eiusmod id sint reprehenderit fugiat commodo labore qui pariatur. Incididunt cupidatat culpa consectetur ipsum nisi mollit non Lorem mollit non pariatur. Cupidatat fugiat tempor ipsum non mollit nostrud deserunt sint et qui.\r\n',
    registered: '2021-04-06T04:31:08 -05:00',
    latitude: -63.314653,
    longitude: -139.331895,
    tags: ['ad', 'ut', 'dolor', 'ipsum', 'anim', 'cillum', 'reprehenderit'],
    friends: [
      {
        id: 0,
        name: 'Holland Hines',
      },
      {
        id: 1,
        name: 'Sabrina Robbins',
      },
      {
        id: 2,
        name: 'Rene Workman',
      },
    ],
    greeting: 'Hello, Cathryn Booth! You have 9 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '678755b1e0e77306148fe3fe',
    index: 6,
    guid: 'dade67c2-13f1-452e-aeb6-44355cbacc2d',
    isActive: false,
    balance: '$3,531.96',
    picture: 'http://placehold.it/32x32',
    age: 37,
    eyeColor: 'brown',
    name: 'Bennett Campbell',
    gender: 'male',
    company: 'KNOWLYSIS',
    email: 'bennettcampbell@knowlysis.com',
    phone: '+1 (804) 406-2418',
    address: '521 Perry Place, Lumberton, Rhode Island, 569',
    about:
      'Ea velit voluptate nostrud reprehenderit cillum cillum Lorem Lorem. Sunt ullamco consequat proident non mollit ullamco anim in nulla. Reprehenderit sunt est commodo Lorem labore. Enim labore commodo cillum deserunt fugiat quis nulla. Ipsum minim duis nisi veniam. Eu aute consequat elit qui adipisicing id irure irure in minim.\r\n',
    registered: '2015-02-18T04:04:31 -05:00',
    latitude: 51.767524,
    longitude: -55.940214,
    tags: ['non', 'tempor', 'in', 'Lorem', 'eiusmod', 'labore', 'aliqua'],
    friends: [
      {
        id: 0,
        name: 'Grace Moreno',
      },
      {
        id: 1,
        name: 'Rutledge Cortez',
      },
      {
        id: 2,
        name: 'Kris Mcpherson',
      },
    ],
    greeting: 'Hello, Bennett Campbell! You have 7 unread messages.',
    favoriteFruit: 'apple',
  },
];
